### ISSUE TITLE
Proper Integration for Mystical Aggradditions

### ISSUE THREAD

**Issue by onyxromero** [BlakeBr0/MysticalCustomization#24]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Ex: I cannot add Insanium Essence seeds. Tier 6 is invalid because it only checks for Tiers in Mystical Agriculture or ones you define in the custom tiers thing. I can add the Insanium Essence seeds under Tier 5, but the problem is it just creates a new essence type all together which isn't usable for anything. I want the Insanium Seeds to produce the proper essence in Mystical Aggradditions.

**Describe the solution you'd like**

Full support for crops in Mystical Aggradditions and other mods like it, like in Mystical Agriculture.

**Comment by BlakeBr0** [comment]
The behavior with the essences is a work around since the generated items use the `mysticalagriculture` namespace and would therefor cause issues. I can add a special case for Insanium essence to make that behavior consistent.

As far as the Tier 6 crop tier, that's an issue with agradditions not registering the crop tier properly. That'll be fixed in the next agradditions update, whenever that comes out.

**Comment by BlakeBr0** [comment]
Customization 3.1.1 makes the insanium crop work like the others, and Agradditions 5.1.1 fixes the issue with the tier 6 crop tier.
