### ISSUE TITLE
baseSecondaryChance is not being altered from its default

### ISSUE THREAD

**Issue by YzXupoo** [BlakeBr0/MysticalCustomization#46]
**Describe the bug**
When adding a new crop for projectE the base secondary drop chance was changed to value 0.0 and the drop chance was still set to the defualt when in game.

**To Reproduce**
{
  "name": "Dark Matter",
  "type": "mysticalagriculture:resource",
  "tier": "mysticalagriculture:5",
  "ingredient": {
    "item": "projecte:dark_matter"
  },
  "textures": {
    "flower": "mysticalagriculture:block/flower_ingot",
    "essence": "mysticalagriculture:item/essence_ingot"
    "seeds": "mysticalagriculture:item/mystical_seeds"
  },
    "baseSecondaryChance": 0.0,
    "essence":"projecte:dark_matter"

}

**Expected behavior**
Expected the base chance to be 0.0, but it is still 10%

**Screenshots / Scripts / Logs**
No errors or anything like that. Just trying to set the seed to only be craftable and growing, but not increasing in seed numbers without crafting.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: 7.0.7
 - Mystical Agriculture: 7.0.10
 - Mystical Customization: 5.0.0
 - Singleplayer or Multiplayer: singplayer

**Comment by BlakeBr0** [comment]
So there's essentially two 'chances' that get combined to decide the chance of a secondary seed drop:
- base chance (when planted on essence farmland, set on crop, or falls back to crop tier)
- effective farmland chance (when planted on the farmland block that corresponds with your tier)

Currently you would have to create a new crop tier that doesn't have an effective farmland OR has `secondarySeedDrop` set to `false` and set the crop to that tier to get the effect you want. This is generally the intended approach as that's how tier 6 crops work in Agradditions.

I'll look into making it so that the effective farmland chance can be modified per crop (either toggle or percentage like base).
